name: test macos runner

on: 
    workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-latest
    steps:
    - name: carryout speedtest
      run: |
        networkQuality -s
        system_profiler SPStorageDataType SPHardwareDataType SPSoftwareDataType
