name: test gpu runner

on: 
    workflow_dispatch:

jobs:
  run-script:
    runs-on:
      group: tj-runner-group
      labels: tj-runners
    steps:
    - name: Run nvidia smi
      run: |
        nvidia-smi
