name: test macos runner

on: 
    workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-latest
    steps:
    - name: system info commands
      run: |
        system_profiler SPDisplaysDataType SPStorageDataType SPHardwareDataType SPSoftwareDataType 
